=== api-evangelist/amazon-comprehend/json-schema/openapi.yml-import-model-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-comprehend/refs/heads/main/json-schema/openapi.yml-import-model-request-schema.json",
  "title": "ImportModelRequest",
  "description": "ImportModelRequest schema",
  "type": "object",
  "properties": {
    "SourceModelArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ComprehendModelArn"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the custom model to import."
        }
      ]
    },
    "ModelName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ComprehendArnName"
        },
        {
          "description": "The name to assign to the custom model that is created in Amazon Comprehend by this import."
        }
      ]
    },
    "VersionName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/VersionName"
        },
        {
          "description": "The version name given to the custom model that is created by this import. Version names can have a maximum of 256 characters. Alphanumeric characters, hyphens (-) and underscores (_) are allowed. The version name must be unique among all models with the same classifier name in the account/Region."
        }
      ]
    },
    "ModelKmsKeyId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/KmsKeyId"
        },
        {
          "description": "<p>ID for the KMS key that Amazon Comprehend uses to encrypt trained custom models. The ModelKmsKeyId can be either of the following formats:</p> <ul> <li> <p>KMS Key ID: <code>\"1234abcd-12ab-34cd-56ef-1234567890ab\"</code> </p> </li> <li> <p>Amazon Resource Name (ARN) of a KMS Key: <code>\"arn:aws:kms:us-west-2:111122223333:key/1234abcd-12ab-34cd-56ef-1234567890ab\"</code> </p> </li> </ul>"
        }
      ]
    },
    "DataAccessRoleArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/IamRoleArn"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the IAM role that grants Amazon Comprehend permission to use Amazon Key Management Service (KMS) to encrypt or decrypt the custom model."
        }
      ]
    },
    "Tags": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TagList"
        },
        {
          "description": "Tags to associate with the custom model that is created by this import. A tag is a key-value pair that adds as a metadata to a resource used by Amazon Comprehend. For example, a tag with \"Sales\" as the key might be added to a resource to indicate its use by the sales department."
        }
      ]
    }
  },
  "required": [
    "SourceModelArn"
  ]
}

=== api-evangelist/amazon-comprehend/examples/openapi.yml-import-model-request-example.json
{
  "SourceModelArn": "arn:aws:comprehend:us-east-1:123456789012:document-classifier/MyClassifier",
  "ModelName": "example-name",
  "VersionName": "example-name",
  "ModelKmsKeyId": "example-string",
  "DataAccessRoleArn": "arn:aws:comprehend:us-east-1:123456789012:document-classifier/MyClassifier",
  "Tags": "example-string"
}
