=== api-evangelist/amazon-comprehend/json-schema/openapi.yml-start-key-phrases-detection-job-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-comprehend/refs/heads/main/json-schema/openapi.yml-start-key-phrases-detection-job-request-schema.json",
  "title": "StartKeyPhrasesDetectionJobRequest",
  "description": "StartKeyPhrasesDetectionJobRequest schema",
  "type": "object",
  "properties": {
    "InputDataConfig": {
      "allOf": [
        {
          "$ref": "#/components/schemas/InputDataConfig"
        },
        {
          "description": "Specifies the format and location of the input data for the job."
        }
      ]
    },
    "OutputDataConfig": {
      "allOf": [
        {
          "$ref": "#/components/schemas/OutputDataConfig"
        },
        {
          "description": "Specifies where to send the output files."
        }
      ]
    },
    "DataAccessRoleArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/IamRoleArn"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the IAM role that grants Amazon Comprehend read access to your input data. For more information, see <a href=\"https://docs.aws.amazon.com/comprehend/latest/dg/security_iam_id-based-policy-examples.html#auth-role-permissions\">Role-based permissions</a>."
        }
      ]
    },
    "JobName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/JobName"
        },
        {
          "description": "The identifier of the job."
        }
      ]
    },
    "LanguageCode": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LanguageCode"
        },
        {
          "description": "The language of the input documents. You can specify any of the primary languages supported by Amazon Comprehend. All documents must be in the same language."
        }
      ]
    },
    "ClientRequestToken": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ClientRequestTokenString"
        },
        {
          "description": "A unique identifier for the request. If you don't set the client request token, Amazon Comprehend generates one."
        }
      ]
    },
    "VolumeKmsKeyId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/KmsKeyId"
        },
        {
          "description": "<p>ID for the Amazon Web Services Key Management Service (KMS) key that Amazon Comprehend uses to encrypt data on the storage volume attached to the ML compute instance(s) that process the analysis job. The VolumeKmsKeyId can be either of the following formats:</p> <ul> <li> <p>KMS Key ID: <code>\"1234abcd-12ab-34cd-56ef-1234567890ab\"</code> </p> </li> <li> <p>Amazon Resource Name (ARN) of a KMS Key: <code>\"arn:aws:kms:us-west-2:111122223333:key/1234abcd-12ab-34cd-56ef-1234567890ab\"</code> </p> </li> </ul>"
        }
      ]
    },
    "VpcConfig": {
      "allOf": [
        {
          "$ref": "#/components/schemas/VpcConfig"
        },
        {
          "description": " Configuration parameters for an optional private Virtual Private Cloud (VPC) containing the resources you are using for your key phrases detection job. For more information, see <a href=\"https://docs.aws.amazon.com/vpc/latest/userguide/what-is-amazon-vpc.html\">Amazon VPC</a>. "
        }
      ]
    },
    "Tags": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TagList"
        },
        {
          "description": "Tags to associate with the key phrases detection job. A tag is a key-value pair that adds metadata to a resource used by Amazon Comprehend. For example, a tag with \"Sales\" as the key might be added to a resource to indicate its use by the sales department."
        }
      ]
    }
  },
  "required": [
    "InputDataConfig",
    "OutputDataConfig",
    "DataAccessRoleArn",
    "LanguageCode"
  ]
}

=== api-evangelist/amazon-comprehend/examples/openapi.yml-start-key-phrases-detection-job-request-example.json
{
  "InputDataConfig": "example-string",
  "OutputDataConfig": "example-string",
  "DataAccessRoleArn": "arn:aws:comprehend:us-east-1:123456789012:document-classifier/MyClassifier",
  "JobName": "example-name",
  "LanguageCode": "en",
  "ClientRequestToken": "example-string",
  "VolumeKmsKeyId": "example-string",
  "VpcConfig": "example-string",
  "Tags": "example-string"
}
